name: zksync-ci

on:
    push:
        branches:
            - 'zksync-v**'
    pull_request:
        branches:
            - 'zksync-v**'
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
    CARGO_TERM_COLOR: always

jobs:
    doctests:
        name: doc tests
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@nightly
            - uses: Swatinem/rust-cache@v2
              with:
                cache-on-failure: true
            - name: cargo test
              run: cargo test --doc
              env:
                RUST_TEST_THREADS: 2

    clippy:
        name: clippy
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@clippy
            - uses: Swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
            - run: cargo clippy --workspace --all-targets --all-features
              env:
                  RUSTFLAGS: -Dwarnings

    fmt:
        name: fmt
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                components: rustfmt

            - name: Run rustfmt
              run: cargo fmt -- --check
    
    cargo-test:
        name: cargo-test
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
          - uses: actions/checkout@v4
            with:
              submodules: recursive
              ref: ${{ github.event.pull_request.head.sha }}
          - uses: actions-rust-lang/setup-rust-toolchain@v1
          - uses: Swatinem/rust-cache@v2
            with:
              cache-on-failure: true
          - name: Run tests
            run: cargo test zk
            env:
              RUST_BACKTRACE: full