name: zksync-ci

on:
    push:
        branches:
            - 'zksync-v**'
    pull_request:
        branches:
            - 'zksync-v**'
concurrency:
    cancel-in-progress: true
    group: ${{github.workflow}}-${{github.ref}}

env:
    CARGO_TERM_COLOR: always

jobs:
    doctests:
        name: doc tests
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@nightly
              with:
                toolchain: nightly-2024-04-28
            - uses: Swatinem/rust-cache@v2
              with:
                cache-on-failure: true
            - name: cargo test
              run: cargo test --doc
              env:
                RUST_TEST_THREADS: 2

    clippy:
        name: clippy
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@clippy
            - uses: Swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
            - run: cargo clippy --workspace --all-targets --all-features
              env:
                  RUSTFLAGS: -Dwarnings

    fmt:
        name: fmt
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@nightly
              with:
                  toolchain: nightly-2024-04-28
                  components: rustfmt
            - run: cargo fmt --all --check
    
    cargo-test:
        name: cargo-test
        runs-on: ubuntu-latest
  
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            submodules: recursive
            ref: ${{ github.event.pull_request.head.sha }}
  
        - name: Install Rust
          uses: actions-rust-lang/setup-rust-toolchain@v1
          with:
            toolchain: nightly-2024-04-28

        - name: Run tests
          env:
            RUST_BACKTRACE: full
          run: cargo test